#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════
#  STEP 2: OS Hardening
# ═══════════════════════════════════════════════════════

LOGFILE="/var/log/kintales-setup.log"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [02-hardening] $1" | tee -a "$LOGFILE"; }
ok()  { echo "  ✅ $1"; log "OK: $1"; }
fail() { echo "  ❌ $1"; log "FAIL: $1"; exit 1; }

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  STEP 2: OS Hardening"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "WHY: A fresh Ubuntu install has weak defaults — root login"
echo "     enabled, password SSH allowed, standard port 22. These"
echo "     are the first things attackers try. We create a dedicated"
echo "     admin user, lock down SSH, and enable automatic security"
echo "     patches."
echo ""
echo "RISK WITHOUT THIS: Automated bots find your SSH port within"
echo "     hours and start brute-forcing root password. Default"
echo "     Ubuntu will be compromised within days if exposed."
echo ""
read -p "Press Enter to continue or Ctrl+C to abort..."
echo ""

# ─── Load .env ───────────────────────────────────────

if [ ! -f "$ENV_FILE" ]; then
  fail ".env file not found at $ENV_FILE. Copy .env.example to .env and fill in values."
fi

# shellcheck source=/dev/null
source "$ENV_FILE"

ADMIN_USER="${ADMIN_USER:-kintales}"
SSH_PORT="${SSH_PORT:-2222}"
ADMIN_SSH_PUBKEY="${ADMIN_SSH_PUBKEY:-}"
ADMIN_IP="${ADMIN_IP:-}"

if [ -z "$ADMIN_SSH_PUBKEY" ]; then
  fail "ADMIN_SSH_PUBKEY not set in .env. Generate with: ssh-keygen -t ed25519"
fi

log "Starting OS hardening (user: $ADMIN_USER, SSH port: $SSH_PORT)"

# ─── Create admin user ───────────────────────────────

echo "Creating admin user '$ADMIN_USER'..."
echo ""
echo "WHY: Running as root is dangerous — a single typo can"
echo "     destroy the system. An admin user with sudo provides"
echo "     a safety net (you must type 'sudo' consciously)."

if id "$ADMIN_USER" &>/dev/null; then
  ok "User '$ADMIN_USER' already exists"
else
  adduser --disabled-password --gecos "KinTales Admin" "$ADMIN_USER"
  usermod -aG sudo "$ADMIN_USER"
  ok "User '$ADMIN_USER' created with sudo"
fi

# ─── Set up SSH key ──────────────────────────────────

echo ""
echo "Setting up SSH key authentication..."
echo ""
echo "WHY: SSH keys are far more secure than passwords."
echo "     A 256-bit Ed25519 key has 2^256 possible values —"
echo "     brute-forcing this is computationally impossible."
echo "     Passwords, even good ones, have much less entropy."

SSH_DIR="/home/${ADMIN_USER}/.ssh"
mkdir -p "$SSH_DIR"
echo "$ADMIN_SSH_PUBKEY" > "${SSH_DIR}/authorized_keys"
chmod 700 "$SSH_DIR"
chmod 600 "${SSH_DIR}/authorized_keys"
chown -R "${ADMIN_USER}:${ADMIN_USER}" "$SSH_DIR"

ok "SSH key installed for $ADMIN_USER"

# ─── Disable root login ─────────────────────────────

echo ""
echo "Disabling root login..."
echo ""
echo "WHY: Root is the #1 target for attackers. Disabling root"
echo "     login means even if they guess a password, 'root'"
echo "     username won't work."

passwd -l root
ok "Root login disabled (password locked)"

# ─── Harden SSH ──────────────────────────────────────

echo ""
echo "Hardening SSH configuration..."
echo ""
echo "Changes:"
echo "  Port:                 22 → $SSH_PORT (non-standard port reduces noise)"
echo "  PermitRootLogin:      yes → no"
echo "  PasswordAuthentication: yes → no (keys only)"
echo "  PubkeyAuthentication: yes (confirmed)"
echo "  MaxAuthTries:         6 → 3"
echo "  ClientAliveInterval:  0 → 300 (5 min timeout)"
echo ""
echo "WHY: Port 22 is scanned by millions of bots. Changing to"
echo "     $SSH_PORT eliminates 99% of automated attacks. Combined"
echo "     with key-only auth, this makes SSH practically unbreakable."

SSHD_CONFIG="/etc/ssh/sshd_config"
cp "$SSHD_CONFIG" "${SSHD_CONFIG}.backup.$(date +%Y%m%d)" 2>/dev/null || true

# Write hardened config
cat > "${SSHD_CONFIG}.d/99-kintales-hardening.conf" << EOF
# KinTales SSH Hardening — generated by setup/02-os-hardening.sh
Port $SSH_PORT
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
X11Forwarding no
AllowTcpForwarding no
PermitEmptyPasswords no
Protocol 2
EOF

# Validate SSH config before restarting
if sshd -t; then
  ok "SSH config valid"
else
  fail "SSH config invalid! Check ${SSHD_CONFIG}.d/99-kintales-hardening.conf"
fi

# ─── Set hostname ────────────────────────────────────

echo ""
echo "Setting hostname to 'kintales-prod'..."
hostnamectl set-hostname kintales-prod
ok "Hostname set to kintales-prod"

# ─── Set timezone ────────────────────────────────────

echo ""
echo "Setting timezone to Europe/Sofia..."
echo ""
echo "WHY: Consistent timezone across all logs, cron jobs, and"
echo "     database timestamps. Europe/Sofia (UTC+2/+3) matches"
echo "     our target users in Bulgaria."

timedatectl set-timezone Europe/Sofia
ok "Timezone set to $(timedatectl show --value -p Timezone)"

# ─── Configure NTP ───────────────────────────────────

echo ""
echo "Configuring NTP time sync..."
echo ""
echo "WHY: Accurate time is critical for: SSL certificates,"
echo "     log correlation, TOTP 2FA, database timestamps,"
echo "     and RAID synchronization."

timedatectl set-ntp true
ok "NTP enabled: $(timedatectl show --value -p NTPSynchronized)"

# ─── Enable unattended upgrades ──────────────────────

echo ""
echo "Enabling automatic security updates..."
echo ""
echo "WHY: Security patches are released frequently. Without"
echo "     automatic updates, known vulnerabilities remain"
echo "     unpatched until you manually run apt upgrade."
echo "     Unattended-upgrades only installs SECURITY patches"
echo "     (not feature upgrades), so it's safe for production."

# Enable automatic security updates
cat > /etc/apt/apt.conf.d/20auto-upgrades << EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# Configure to only install security updates and auto-reboot if needed
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

ok "Unattended upgrades configured (security patches only)"

# ─── Restart SSH ─────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  ⚠️  IMPORTANT: Before restarting SSH, verify your"
echo "     access will not be lost!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  New SSH command:"
echo "    ssh $ADMIN_USER@[SERVER_IP] -p $SSH_PORT -i ~/.ssh/your_key"
echo ""
echo "  MAKE SURE you can connect with this command before"
echo "  closing your current session!"
echo ""
read -p "Press Enter to restart SSH or Ctrl+C to abort..."

systemctl restart sshd
ok "SSH restarted on port $SSH_PORT"

# ─── Summary ─────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Step 2 Complete — OS Hardened"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Changes applied:"
echo "    Admin user:    $ADMIN_USER (with sudo)"
echo "    Root login:    disabled"
echo "    SSH port:      $SSH_PORT"
echo "    SSH auth:      key-only (no passwords)"
echo "    Hostname:      kintales-prod"
echo "    Timezone:      Europe/Sofia"
echo "    NTP:           enabled"
echo "    Auto-updates:  security patches only"
echo ""
echo "  ⚠️  TEST NOW (in a new terminal):"
echo "    ssh $ADMIN_USER@[SERVER_IP] -p $SSH_PORT"
echo ""
echo "  Do NOT close this session until you confirm SSH works!"
echo ""
echo "  Next step: Read docs/LUKS-GUIDE.md, then:"
echo "    sudo bash setup/03-luks-encryption.sh"
echo ""

log "Step 2 completed successfully"
