#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════
#  STEP 6: Fail2ban Configuration
# ═══════════════════════════════════════════════════════

LOGFILE="/var/log/kintales-setup.log"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [06-fail2ban] $1" | tee -a "$LOGFILE"; }
ok()  { echo "  ✅ $1"; log "OK: $1"; }

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  STEP 6: Fail2ban — Brute Force Protection"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "WHY: Even with UFW blocking most traffic, determined attackers"
echo "     can still reach SSH (from your admin IP range) and HTTP"
echo "     (through Cloudflare). Fail2ban monitors login attempts"
echo "     and automatically bans IPs after too many failures."
echo ""
echo "     Think of it as a bouncer: the firewall is the locked door,"
echo "     fail2ban is the bouncer who kicks out anyone trying to"
echo "     pick the lock."
echo ""
echo "RISK WITHOUT THIS: An attacker who knows your SSH port could"
echo "     try millions of passwords. Even with key-only auth,"
echo "     the connection attempts waste resources and fill logs."
echo ""
read -p "Press Enter to continue or Ctrl+C to abort..."
echo ""

# ─── Load .env ───────────────────────────────────────

if [ -f "$ENV_FILE" ]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
fi

SSH_PORT="${SSH_PORT:-2222}"

log "Starting fail2ban configuration"

# ─── Check: fail2ban installed ───────────────────────

if ! command -v fail2ban-client &>/dev/null; then
  echo "Installing fail2ban..."
  apt-get install -y fail2ban
fi
ok "fail2ban installed"

# ─── Create jail configuration ───────────────────────

echo "Configuring fail2ban jails..."
echo ""
echo "Jails to configure:"
echo "  1. SSH:       5 failed attempts → 15 min ban"
echo "  2. HTTP auth: 20 failed requests/min → 10 min ban"
echo "  3. Recidive:  repeat offenders → 1 week ban"

cat > /etc/fail2ban/jail.local << EOF
# KinTales fail2ban configuration
# Generated by setup/06-fail2ban.sh

[DEFAULT]
# Ban duration: 15 minutes
bantime = 900
# Detection window: 10 minutes
findtime = 600
# Max attempts before ban
maxretry = 5
# Action: ban IP in UFW
banaction = ufw

# ─── SSH Jail ─────────────────────────────────────────
[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 900
findtime = 600

# ─── Nginx HTTP Auth Jail ─────────────────────────────
# Catches brute-force attacks on API authentication endpoints
[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /data/docker/containers/*/\*-json.log
maxretry = 20
findtime = 60
bantime = 600

# ─── Recidive Jail ────────────────────────────────────
# Bans repeat offenders for 1 week
# If an IP gets banned 3 times in 48 hours, ban for 1 week
[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
banaction = ufw
maxretry = 3
findtime = 172800
bantime = 604800
EOF

ok "Jail configuration written to /etc/fail2ban/jail.local"

# ─── Restart fail2ban ────────────────────────────────

echo ""
echo "Restarting fail2ban..."
systemctl enable fail2ban
systemctl restart fail2ban

# Wait for startup
sleep 2

ok "fail2ban restarted"

# ─── Verify ──────────────────────────────────────────

echo ""
echo "Verifying jail status..."
echo ""

fail2ban-client status

echo ""
for jail in sshd recidive; do
  echo "  Jail: $jail"
  fail2ban-client status "$jail" 2>/dev/null | grep -E "Currently|Total" | sed 's/^/    /' || echo "    (not active yet)"
  echo ""
done

# ─── Summary ─────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Step 6 Complete — Fail2ban Active"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Active jails:"
echo "    sshd:       5 fails → 15 min ban"
echo "    nginx-http: 20 fails/min → 10 min ban"
echo "    recidive:   3 bans → 1 week ban"
echo ""
echo "  Monitor: fail2ban-client status"
echo "  Unban:   fail2ban-client set sshd unbanip [IP]"
echo ""
echo "  Next step: sudo bash setup/07-docker.sh"
echo ""

log "Step 6 completed successfully"
